"""add_call_cost_table

Revision ID: 50e89dd070cb
Revises: 002_new_schema
Create Date: 2026-03-05 15:01:26.432814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '50e89dd070cb'
down_revision: Union[str, None] = '002_new_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('patient_phone', sa.String(length=50), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_organization_id'), 'call_logs', ['organization_id'], unique=False)
    op.create_table('call_cost',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('tts_characters', sa.Integer(), nullable=False),
    sa.Column('llm_input_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_output_tokens', sa.Integer(), nullable=False),
    sa.Column('stt_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('tts_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('llm_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('livekit_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['call_session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_cost_organization_id'), 'call_cost', ['organization_id'], unique=False)
    op.create_index(op.f('ix_call_cost_session_id'), 'call_cost', ['session_id'], unique=True)
    op.alter_column('admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('admins_organization_id_fkey'), 'admins', type_='foreignkey')
    op.alter_column('ai_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('ai_configurations_organization_id_key'), 'ai_configurations', type_='unique')
    op.drop_index(op.f('ix_ai_configurations_organization_id'), table_name='ai_configurations')
    op.create_index(op.f('ix_ai_configurations_organization_id'), 'ai_configurations', ['organization_id'], unique=True)
    op.alter_column('appointment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_appointment_org_id'), table_name='appointment')
    op.drop_index(op.f('ux_doctor_appointment_time'), table_name='appointment', postgresql_where="(app_status <> ALL (ARRAY['Cancelled'::appointment_status_enum, 'NoShow'::appointment_status_enum]))")
    op.create_index(op.f('ix_appointment_organization_id'), 'appointment', ['organization_id'], unique=False)
    op.alter_column('call_session', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('call_session', 'confidence_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('ix_call_session_org_id'), table_name='call_session')
    op.drop_index(op.f('ix_call_session_phone'), table_name='call_session')
    op.create_index(op.f('ix_call_session_organization_id'), 'call_session', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_doc_shift_org_id'), table_name='doc_shift')
    op.create_index(op.f('ix_doc_shift_organization_id'), 'doc_shift', ['organization_id'], unique=False)
    op.alter_column('doctor', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctor', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_doctor_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_org_id'), table_name='doctor')
    op.create_index(op.f('ix_doctor_organization_id'), 'doctor', ['organization_id'], unique=False)
    op.drop_column('doctor', 'address')
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_patient_org_id'), table_name='patient')
    op.create_index(op.f('ix_patient_organization_id'), 'patient', ['organization_id'], unique=False)
    op.alter_column('patient_account', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient_account', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_patient_account_mobile'), table_name='patient_account')
    op.drop_index(op.f('ix_patient_account_org_id'), table_name='patient_account')
    op.drop_constraint(op.f('uq_patient_account_org_mobile'), 'patient_account', type_='unique')
    op.create_index(op.f('ix_patient_account_organization_id'), 'patient_account', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_patient_memory_org_id'), table_name='patient_memory')
    op.create_index(op.f('ix_patient_memory_organization_id'), 'patient_memory', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_specialty_name'), table_name='specialty')
    op.drop_index(op.f('ix_specialty_org_id'), table_name='specialty')
    op.create_index(op.f('ix_specialty_organization_id'), 'specialty', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_symptoms_name'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_org_id'), table_name='symptoms')
    op.create_index(op.f('ix_symptoms_organization_id'), 'symptoms', ['organization_id'], unique=False)
    op.alter_column('user_memory', 'last_call',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_memory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_memory', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_user_memory_approved'), table_name='user_memory', postgresql_where='(is_approved = true)')
    op.drop_index(op.f('ix_user_memory_email'), table_name='user_memory')
    op.drop_index(op.f('ix_user_memory_last_call'), table_name='user_memory')
    op.drop_index(op.f('ix_user_memory_org_id'), table_name='user_memory')
    op.drop_constraint(op.f('uq_user_memory_org_phone'), 'user_memory', type_='unique')
    op.create_index(op.f('ix_user_memory_organization_id'), 'user_memory', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_memory_organization_id'), table_name='user_memory')
    op.create_unique_constraint(op.f('uq_user_memory_org_phone'), 'user_memory', ['organization_id', 'phone_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_memory_org_id'), 'user_memory', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_memory_last_call'), 'user_memory', ['last_call'], unique=False)
    op.create_index(op.f('ix_user_memory_email'), 'user_memory', ['email'], unique=False)
    op.create_index(op.f('idx_user_memory_approved'), 'user_memory', ['is_approved'], unique=False, postgresql_where='(is_approved = true)')
    op.alter_column('user_memory', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_memory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_memory', 'last_call',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_symptoms_organization_id'), table_name='symptoms')
    op.create_index(op.f('ix_symptoms_org_id'), 'symptoms', ['organization_id'], unique=False)
    op.create_index(op.f('ix_symptoms_name'), 'symptoms', ['sym_name'], unique=False)
    op.drop_index(op.f('ix_specialty_organization_id'), table_name='specialty')
    op.create_index(op.f('ix_specialty_org_id'), 'specialty', ['organization_id'], unique=False)
    op.create_index(op.f('ix_specialty_name'), 'specialty', ['spec_name'], unique=False)
    op.drop_index(op.f('ix_patient_memory_organization_id'), table_name='patient_memory')
    op.create_index(op.f('ix_patient_memory_org_id'), 'patient_memory', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_patient_account_organization_id'), table_name='patient_account')
    op.create_unique_constraint(op.f('uq_patient_account_org_mobile'), 'patient_account', ['organization_id', 'mobile_no'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_patient_account_org_id'), 'patient_account', ['organization_id'], unique=False)
    op.create_index(op.f('ix_patient_account_mobile'), 'patient_account', ['mobile_no'], unique=False)
    op.alter_column('patient_account', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient_account', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_patient_organization_id'), table_name='patient')
    op.create_index(op.f('ix_patient_org_id'), 'patient', ['organization_id'], unique=False)
    op.alter_column('patient', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patient', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('doctor', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_doctor_organization_id'), table_name='doctor')
    op.create_index(op.f('ix_doctor_org_id'), 'doctor', ['organization_id'], unique=False)
    op.create_index(op.f('ix_doctor_name'), 'doctor', ['name'], unique=False)
    op.alter_column('doctor', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('doctor', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_doc_shift_organization_id'), table_name='doc_shift')
    op.create_index(op.f('ix_doc_shift_org_id'), 'doc_shift', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_call_session_organization_id'), table_name='call_session')
    op.create_index(op.f('ix_call_session_phone'), 'call_session', ['phone_number'], unique=False)
    op.create_index(op.f('ix_call_session_org_id'), 'call_session', ['organization_id'], unique=False)
    op.alter_column('call_session', 'confidence_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('call_session', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_appointment_organization_id'), table_name='appointment')
    op.create_index(op.f('ux_doctor_appointment_time'), 'appointment', ['doctor_id', 'date_time'], unique=True, postgresql_where="(app_status <> ALL (ARRAY['Cancelled'::appointment_status_enum, 'NoShow'::appointment_status_enum]))")
    op.create_index(op.f('ix_appointment_org_id'), 'appointment', ['organization_id'], unique=False)
    op.alter_column('appointment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ai_configurations_organization_id'), table_name='ai_configurations')
    op.create_index(op.f('ix_ai_configurations_organization_id'), 'ai_configurations', ['organization_id'], unique=False)
    op.create_unique_constraint(op.f('ai_configurations_organization_id_key'), 'ai_configurations', ['organization_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ai_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(op.f('admins_organization_id_fkey'), 'admins', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_call_cost_session_id'), table_name='call_cost')
    op.drop_index(op.f('ix_call_cost_organization_id'), table_name='call_cost')
    op.drop_table('call_cost')
    op.drop_index(op.f('ix_call_logs_organization_id'), table_name='call_logs')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
