"""Add SuperAdmin, TenantSubscription, and AI model config

Revision ID: 89a6edc0ba69
Revises: 72086ec03fc9
Create Date: 2026-03-19 11:17:34.863695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89a6edc0ba69'
down_revision: Union[str, None] = '72086ec03fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    op.create_table('tenant_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('max_api_calls', sa.Integer(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_subscriptions_organization_id'), 'tenant_subscriptions', ['organization_id'], unique=True)
    op.add_column('ai_configurations', sa.Column('llm_provider', sa.String(length=50), server_default='openai', nullable=False))
    op.add_column('ai_configurations', sa.Column('llm_model', sa.String(length=100), server_default='gpt-4o-mini', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_configurations', 'llm_model')
    op.drop_column('ai_configurations', 'llm_provider')
    op.drop_index(op.f('ix_tenant_subscriptions_organization_id'), table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.drop_table('super_admins')
    # ### end Alembic commands ###
